version: '3.8'

services:
  cognito-unit-test:
    image: cognito-nest-uni
    build:
      context: ../
      dockerfile: docker-development/unit/Dockerfile
    env_file:
      - .env  
    volumes:
      - ../package/src:/package/src
      - ../package/tests:/package/tests