name: Check unit tests

on:
  - push
  - pull_request

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: /package
        run: |
          npm install

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        working-directory: /package
        run: |
          npm run test
  run-eslin:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        working-directory: /package
        run: |
          npm run lint-test
