name: Check unit tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ./package/node_modules
          key: npm-${{ hashFiles('./package/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        working-directory: ./package
        run: |
          npm install

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy node_modules from workspace
        run: |
          cp -R ${{ github.workspace }}/package/node_modules ./package/

      - name: Run tests
        working-directory: ./package
        run: |
          npm run test

  run-eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy node_modules from workspace
        run: |
          cp -R ${{ github.workspace }}/package/node_modules ./package/

      - name: Run eslint
        working-directory: ./package
        run: |
          npm run lint-test
